### ISSUE TITLE
Performance always shows 0% bug or config

### ISSUE THREAD

**Issue by evertonbtm** [lildude/ha-addon-ghostfolio#66] opened 2024-07-25 05:16 UTC
Hi,
I'm trying to show my performance but its always a zero, it's a configuration or i have a bug?

I use BRL currency and Brazil stocks market.
version: 2.97.0

**Comment by lildude** [comment] 2024-07-25 07:02
You're asking the wrong person 😁 You'll want to ask the [Ghostfolio](https://github.com/ghostfolio/ghostfolio) peeps. I just repackage their app for HA.

Closing as this is about Ghostfolio functionally/behaviour not the addon functionality/behaviour.

**Comment by evertonbtm** [comment] 2024-07-25 10:28
hi, yes! i ask the repo too!  but its a kinda strange the image deployed on docker out of HA with the same database works.
thanks!

**Comment by lildude** [comment] 2024-07-25 10:40
🤔 Do you have a simple way of reproducing this so I can see if I can reproduce it too?

**Comment by evertonbtm** [comment] 2024-07-25 12:24
I've thinked its a data problem but  using USD same problem occurs on new tests, a little icon on home page show up this message:
'Oops! data provider is experiencing the hiccups.'  
You are right, maybe some problem to call api data fetch

**Comment by lildude** [comment] 2024-07-25 13:06
I've not exposed a method to enable debug logging as I don't know how to do this 😁 If you disable the silent option you should get the normal Ghostfolio logs though.

**Comment by lildude** [comment] 2024-07-25 13:06
Going to reopen this until we get to the bottom of it.

**Comment by lildude** [comment] 2024-07-25 13:47
I've just tested using a dev environment using [this sample import file](https://github.com/ghostfolio/ghostfolio/blob/main/test/import/ok-500-activities.json) from the ghostfolio repo and things are working for me:

![Image](https://github.com/user-attachments/assets/afa88a1f-40cb-498f-946d-5977e89b2af1)

**Comment by evertonbtm** [comment] 2024-07-27 20:09
hi,

i  started debugging the application and i found a problem on market price fetch, its occurs by date problem. I don't know how its works, for the moment i stoped using addon and deploy a docker version.

thanks for help.

**Comment by lildude** [comment] 2024-07-28 07:34
🤔 this should work the same as the addon is wrapping the docker image without modifying it so it works on HA.

Are you able to provide a small sample export that replicates the issue? I don't need your full portfolio, just enough dummy transactions to show the problem.

> i started debugging the application and i found a problem on market price fetch, its occurs by date problem.

Do you have a link to the code where you think the problem is? I might be able to work something out from that.

**Comment by evertonbtm** [comment] 2024-07-28 15:31
I opened a issue on main repository with details, follow link https://github.com/ghostfolio/ghostfolio/issues/3616, later i export sample dat and post here.

**Comment by evertonbtm** [comment] 2024-07-28 15:56
someone mentioned this thread: https://forums.unraid.net/topic/123829-support-community-applications-ghostfolio/page/3/#comment-1169817

**Comment by evertonbtm** [comment] 2024-07-29 11:10
nice! thanks so much.

**Closed** 2024-07-29 15:16 UTC

**Comment by lildude** [comment] 2024-07-29 15:19
I reproduced the issue using your timezone and found forcing things to UTC resolved the issue.

There shouldn't be a problem with this as I don't think anything uses time within the data presented to the user. If necessary, the new env_vars option will allow us to easily unset or override this.

I've just release v1.22.0 which updates Ghostfolio to v2.98.0 and also now forces the addon to use the UTC timezone.

**Comment by evertonbtm** [comment] 2024-07-29 15:44
Thanks! Now it works perfectly
